name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
     contents: write
     
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            targets: x86_64-unknown-linux-gnu
            platforms: linux-x64
            shell: bash
          - os: macos-latest
            targets: x86_64-apple-darwin,aarch64-apple-darwin
            platforms: osx-x64,osx-arm64
            shell: bash

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Ensure consistent line endings
          fetch-depth: 0
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.targets }}
      
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Make Script Executable
        shell: bash
        run: chmod +x ./build-rust.sh
      
      - name: Build Rust Library
        shell: bash
        run: ./build-rust.sh --platforms ${{ matrix.platforms }}
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: native-libs-${{ matrix.os }}
          path: HyperTrieCore/target/release/
          if-no-files-found: error

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: HyperTrieCore/target/release/
          pattern: native-libs-*
          merge-multiple: true
      
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Build .NET Project
        run: |
          cd HyperTrieCore/src/HyperTrieCore
          dotnet build -c Release

      - name: Build and Pack NuGet Package
        run: |
          cd HyperTrieCore/src/HyperTrieCore
          dotnet pack -c Release
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: HyperTrieCore/src/HyperTrieCore/bin/Release/*.nupkg
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 